package views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author chris
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener{

    private JMenuBar barra;
    private JMenu archivo,ventas,clientes,motos,registros,acerca;
    private JMenuItem itemLogin, itemCliente, itemMoto, itemVenta;
    private final String PANEL_CLIENTES = "Clientes";
    private final String PANEL_VENTAS = "Ventas";
    private final String PANEL_MOTOS = "Motos";

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        setVisible(true);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(d.width/3,d.height/5);
        anadirMenu();
        initComponents();
        panelIndicador.setBackground(Color.RED);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pack();
    }


    public void anadirMenu(){
        barra = new JMenuBar();
        archivo = new JMenu("Login");
        ventas = new JMenu("Ventas");
        clientes = new JMenu("Clientes");
        motos = new JMenu("Motos");
        registros = new JMenu("Registros");
        acerca = new JMenu("Acerca de");

        itemLogin = new JMenuItem("Iniciar sesion");
        archivo.add(itemLogin);
        itemLogin.addActionListener(this);
        barra.add(archivo);
        barra.add(ventas);
        barra.add(clientes);
        barra.add(motos);
        barra.add(registros);
        barra.add(acerca);
        setJMenuBar(barra);
    }

    public void anadirElementos(String nombre){

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == itemLogin){
            System.out.println("archivo");
        }
    }

    public void mostrarPaneles(String panel){
        switch(panel){
            case PANEL_CLIENTES:

                break;
            case PANEL_MOTOS:

                break;
            case PANEL_VENTAS:

                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        panelIncial = new javax.swing.JPanel();
        panelClientes = new javax.swing.JPanel();
        panelIndicador = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelIncial.setBackground(new java.awt.Color(204, 204, 204));
        panelIncial.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
                panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        panelClientesLayout.setVerticalGroup(
                panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 295, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelIncialLayout = new javax.swing.GroupLayout(panelIncial);
        panelIncial.setLayout(panelIncialLayout);
        panelIncialLayout.setHorizontalGroup(
                panelIncialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelIncialLayout.setVerticalGroup(
                panelIncialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelIncial, java.awt.BorderLayout.CENTER);

        panelIndicador.setPreferredSize(new java.awt.Dimension(600, 5));

        javax.swing.GroupLayout panelIndicadorLayout = new javax.swing.GroupLayout(panelIndicador);
        panelIndicador.setLayout(panelIndicadorLayout);
        panelIndicadorLayout.setHorizontalGroup(
                panelIndicadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        panelIndicadorLayout.setVerticalGroup(
                panelIndicadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        getContentPane().add(panelIndicador, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenu jMenu1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelIncial;
    private javax.swing.JPanel panelIndicador;
    // End of variables declaration
}
