package views.paneles;

import java.io.File;

public class panelPrincipal extends javax.swing.JPanel {

    private final String RUTA_REC =  System.getProperty("user.dir")+
            File.separator+"src"+File.separator+"views"
            +File.separator+"Imagenes"+File.separator;

    public panelPrincipal() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 300));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(RUTA_REC+"welcomelogo (1).png")); // NOI18N
        add(jLabel1, new java.awt.GridBagConstraints());
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}