/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Ventanas.Interfaces;

import controllers.ControllerConexion;
import views.Ventanas.Paneles.Clientes;
import views.Ventanas.Paneles.Motos;
import views.Ventanas.Paneles.Usuarios;
import views.Ventanas.Paneles.Ventas;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author chris
 */
public class mainInterface extends javax.swing.JFrame implements ActionListener{

    private JMenuBar barra;
    private JMenu menu_archivo, menu_opciones, menu_ayuda, menu_acerca;
    private JMenuItem abrirBBDD,generarPDF,estadistica;
    private JMenuItem rutaFicheros, cambiarTema,verConexion,cerrarSesion;
    private JMenuItem infoConsulta,infoElimina, infoModif, infoInsertar;
    private JMenuItem quienesSomos, contacto;
    private Usuarios panelUsuario;
    private Clientes panelClientes;
    private Motos panelMotos;
    private Ventas panelVentas;
    private final String PANEL_USUARIO = "usuario";
    private final String PANEL_CLIENTE = "cliente";
    private final String PANEL_MOTO = "moto";
    private final String PANEL_VENTA = "venta";
    private int nivelUsuario;
    private ControllerConexion conexion;
    private String ruta = System.getProperty("user.dir")+
            File.separator+"src"+File.separator+"Imagenes"+File.separator;

    public mainInterface() {
        initComponents();
        anadirMenu();
        pack();
        this.panelClientes = new Clientes(nivelUsuario);
        this.panelMotos = new Motos();
        this.panelUsuario = new Usuarios();
        this.panelVentas = new Ventas();
        setTitle("Concesionario Mercado Del Corral");
        anadirPaneles();
        botonVentas.addActionListener(this);
        botonClientes.addActionListener(this);
        botonMotos.addActionListener(this);
        botonUsuarios.addActionListener(this);
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    public mainInterface(int nivelUsuario, ControllerConexion conexion){
        this.nivelUsuario = nivelUsuario;
        this.conexion = conexion;
        initComponents();
        anadirMenu();
        anadirPaneles();
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setTitle("Concesonario Mercado Corral");



        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        logoMain = new javax.swing.JLabel();
        botonVentas = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        botonMotos = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        panelSecundario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        logoMain.setIcon(new javax.swing.ImageIcon(ruta+"imagenLogo (Personalizado)_1.png")); // NOI18N
        logoMain.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 3;
        jPanel1.add(logoMain, gridBagConstraints);

        botonVentas.setText("Ventas");
        botonVentas.setPreferredSize(new Dimension(90, 30));
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(37, 2, 19, 2);
        jPanel1.add(botonVentas, gridBagConstraints);

        botonClientes.setText("Clientes");
        botonClientes.setPreferredSize(new Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 2, 26, 2);
        jPanel1.add(botonClientes, gridBagConstraints);

        botonMotos.setText("Motos");
        botonMotos.setPreferredSize(new Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 2, 26, 2);
        jPanel1.add(botonMotos, gridBagConstraints);

        botonUsuarios.setText("Usuarios");
        botonUsuarios.setPreferredSize(new Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 2, 26, 2);
        jPanel1.add(botonUsuarios, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelSecundario.setBackground(new java.awt.Color(153, 255, 153));
        panelSecundario.setForeground(new java.awt.Color(204, 255, 204));
        panelSecundario.setPreferredSize(new java.awt.Dimension(600, 300));
        panelSecundario.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelSecundario, java.awt.BorderLayout.CENTER);

        this.panelClientes = new Clientes(nivelUsuario);
        this.panelMotos = new Motos();
        this.panelUsuario = new Usuarios();
        this.panelVentas = new Ventas();

        botonVentas.addActionListener(this);
        botonVentas.addActionListener(this);
        botonClientes.addActionListener(this);
        botonMotos.addActionListener(this);
        botonUsuarios.addActionListener(this);

    }// </editor-fold>

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainInterface().setVisible(true);
            }
        });
    }

    private void anadirMenu(){
        barra = new JMenuBar();

        //Código para la pestaña de archivo
        menu_archivo = new JMenu("Archivo");
        barra.add(menu_archivo);
        abrirBBDD = new JMenuItem("Abrir BBDD");
        generarPDF = new JMenuItem("Generar PDF");
        estadistica = new JMenuItem("Ver estadísticas");
        menu_archivo.add(abrirBBDD);
        menu_archivo.add(generarPDF);
        menu_archivo.add(estadistica);

        //Código para la pestaña de opciones
        menu_opciones = new JMenu("Opciones");
        barra.add(menu_opciones);
        rutaFicheros = new JMenuItem("Cambiar ruta de ficheros");
        cambiarTema = new JMenuItem("Cambiar tema");
        verConexion = new JMenuItem("Datos sobre la conexión");
        cerrarSesion = new JMenuItem("Cerrar la sesión");
        menu_opciones.add(rutaFicheros);
        menu_opciones.add(verConexion);
        menu_opciones.add(cambiarTema);
        menu_opciones.add(cerrarSesion);

        //Código del menu ayuda
        menu_ayuda = new JMenu("Ayuda");
        barra.add(menu_ayuda);
        infoConsulta = new JMenuItem("Cómo consultar");
        infoElimina = new JMenuItem("Cómo eliminar");
        infoModif = new JMenuItem("Cómo modificar");
        infoInsertar = new JMenuItem("Cómo insertar");
        menu_ayuda.add(infoInsertar);
        menu_ayuda.add(infoConsulta);
        menu_ayuda.add(infoModif);
        menu_ayuda.add(infoElimina);

        //Código del menu acerca de
        menu_acerca = new JMenu("Acerca de");
        barra.add(menu_acerca);
        quienesSomos = new JMenuItem("Quiénes somos?");
        contacto = new JMenuItem("Contacta con nosotros!");
        menu_acerca.add(quienesSomos);
        menu_acerca.add(contacto);

        setJMenuBar(barra);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonMotos;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JButton botonVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoMain;
    private javax.swing.JPanel panelSecundario;
    // End of variables declaration

    private void anadirPaneles(){
        panelSecundario.add(panelClientes);
        panelSecundario.add(panelMotos);
        panelSecundario.add(panelVentas);
        panelSecundario.add(panelUsuario);
        panelClientes.setVisible(false);
        panelMotos.setVisible(false);
        panelVentas.setVisible(false);
        panelUsuario.setVisible(false);
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        JButton boton = (JButton) ae.getSource();
        if(boton == botonClientes){
            cambiarPanel(PANEL_CLIENTE);

        }else if(boton == botonMotos){
            cambiarPanel(PANEL_MOTO);

        }else if(boton == botonVentas){
            cambiarPanel(PANEL_VENTA);

        }else if(boton == botonUsuarios){
            cambiarPanel(PANEL_USUARIO);

        }

    }


    public void cambiarPanel(String panelCambio){

        ocultar();
        anadirPaneles();
        switch(panelCambio){
            case PANEL_CLIENTE:

                panelClientes.fillTable();
                panelSecundario.add(panelClientes);
                this.panelClientes.setVisible(true);
                panelSecundario.repaint();
                mostrar();
                break;
            case PANEL_MOTO:
                panelMotos.fillTable();
                panelSecundario.add(panelMotos);
                this.panelMotos.setVisible(true);
                panelSecundario.repaint();
                mostrar();
                break;
            case PANEL_USUARIO:
                panelUsuario.fillTable();
                panelSecundario.add(panelUsuario);
                this.panelUsuario.setVisible(true);
                panelSecundario.repaint();
                mostrar();
                break;
            case PANEL_VENTA:
                panelVentas.fillTable();
                panelSecundario.add(panelVentas);
                this.panelVentas.setVisible(true);
                panelSecundario.repaint();
                mostrar();
                break;
        }
    }

    public void ocultar(){
        Thread t = new Thread(new esconderPanel(this));
        t.start();
        panelClientes.setVisible(false);
        panelMotos.setVisible(false);
        panelVentas.setVisible(false);
        panelUsuario.setVisible(false);
    }

    public void mostrar(){
        Thread o = new Thread(new mostrarPanel(this));
        o.start();
    }

    class esconderPanel implements Runnable{

        private JFrame panel;
        //private JPanel referencia;

        public esconderPanel(JFrame panelCambio){
            this.panel = panelCambio; //Panel que va a sufrir el cambio
        }

        @Override
        public void run() {
            int n = 850;

            while(n > 260){
                panel.setSize(n, panel.getHeight());
                panel.repaint();
                n-=15;
                try{
                    Thread.sleep(1);
                }catch(InterruptedException io){
                    System.out.println(io.getMessage());
                }
            }
            panel.repaint();
//       while(n < tamOriginal){
//           panel.setSize(n, panel.getHeight());
//           n+=15;
//           try{
//                Thread.sleep(1);
//           }catch(InterruptedException io){}
//       }
        }
    }

    class mostrarPanel implements Runnable{

        private JFrame panel;

        public mostrarPanel(JFrame panelCambio){
            this.panel = panelCambio; //Panel que va a sufrir el cambio
        }

        @Override
        public void run() {
            try{
                Thread.sleep(250);
                int n = 260;
                while(n < 865){
                    panel.setSize(n,panel.getHeight());
                    n += 15;
                    panel.repaint();
                    Thread.sleep(1);
                }
            } catch(InterruptedException e){
                System.out.println(e.getMessage());
            }
            panel.repaint();
        }
    }
}


    
    
    
    
    


