/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Ventanas.Interfaces;

import controllers.ControllerConexion;
import controllers.UsuarioCRUD;
import controllers.VentaCRUD;
import views.Ventanas.Paneles.Clientes;
import views.Ventanas.Paneles.Motos;
import views.Ventanas.Paneles.Usuarios;
import views.Ventanas.Paneles.Ventas;
import views.Ventanas.panelesMenu.contacto;
import views.Ventanas.panelesMenu.generadorGraficos;
import views.Ventanas.panelesMenu.generadorPDF;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.*;

/**
 *
 * @author chris
 */
public class mainInterface extends javax.swing.JFrame implements ActionListener{

    private JMenuBar barra;
    private String nombreUsuario;
    private JMenu menu_archivo, menu_opciones, menu_ayuda, menu_acerca;
    private JMenuItem abrirBBDD,generarPDF,estadistica;
    private JMenuItem rutaFicheros, cambiarTema,verConexion,cerrarSesion;
    private JMenuItem infoConsulta,infoElimina, infoModif, infoInsertar;
    private JMenuItem quienesSomos, contactoNosotros;
    private Usuarios panelUsuario;
    private Clientes panelClientes;
    private Motos panelMotos;
    private Ventas panelVentas;
    private UsuarioCRUD cnUser;
    private VentaCRUD cnVentas;
    private final String PANEL_USUARIO = "usuario";
    private final String PANEL_CLIENTE = "cliente";
    private final String PANEL_MOTO = "moto";
    private final String PANEL_VENTA = "venta";
    private int nivelUsuario;
    private int tema;
    private final Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    private ControllerConexion conexion;
    private String ruta =System.getProperty("user.dir")+
            File.separator+"src"+File.separator+"views"+File.separator
            +"Imagenes"+ File.separator;
    boolean modoOscuro = false;

    public mainInterface() {
        this.nivelUsuario = 1;
        this.conexion = new ControllerConexion();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        pack();
    }

    public mainInterface(int nivelUsuario, String nombreUsuario, ControllerConexion conexion){
        this.nivelUsuario = nivelUsuario;
        this.conexion = conexion;
        this.nombreUsuario = nombreUsuario;

        initComponents();
        alterarPermisos();
        setLocation(d.width/4+d.width/32,d.height/4);
        setResizable(false);
        setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setTitle("Concesonario Mercado Corral");
        Image icono = Toolkit.getDefaultToolkit().getImage(ruta+"icono.png");
        setIconImage(icono);
        JLabel imagenLoco = new JLabel();
        imagenLoco.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(ruta + "motoamarillalogo.png")));

        java.awt.GridBagConstraints gridBagConstraints;

        cnUser = new UsuarioCRUD();
        cnVentas = new VentaCRUD();
        jPanel1 = new javax.swing.JPanel();
        logoMain = new javax.swing.JLabel();
        botonVentas = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        botonMotos = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        botonUsuarios.setEnabled(false);
        panelSecundario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        logoMain.setIcon(new javax.swing.ImageIcon(ruta+"imagenLogo (Personalizado)_1.png")); // NOI18N
        logoMain.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 3;
        jPanel1.add(logoMain, gridBagConstraints);

        botonVentas.setText("Ventas");
        botonVentas.setPreferredSize(new Dimension(90, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(37, 2, 19, 2);
        jPanel1.add(botonVentas, gridBagConstraints);

        botonClientes.setText("Clientes");
        botonClientes.setPreferredSize(new Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 2, 26, 2);
        jPanel1.add(botonClientes, gridBagConstraints);

        botonMotos.setText("Motos");
        botonMotos.setPreferredSize(new Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 2, 26, 2);
        jPanel1.add(botonMotos, gridBagConstraints);

        botonUsuarios.setText("Usuarios");
        botonUsuarios.setPreferredSize(new Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 2, 26, 2);
        jPanel1.add(botonUsuarios, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        JLabel nuevaFoto = new JLabel();
        nuevaFoto.setIcon(new ImageIcon(ruta+"fotoPrincipal.jpg"));
        panelSecundario.setPreferredSize(new java.awt.Dimension(600, 300));
        panelSecundario.setLayout(new java.awt.BorderLayout());
        panelSecundario.add(nuevaFoto);
        getContentPane().add(panelSecundario, java.awt.BorderLayout.CENTER);

        this.panelClientes = new Clientes(nivelUsuario);
        this.panelMotos = new Motos(nivelUsuario);
        this.panelUsuario = new Usuarios(nivelUsuario);
        this.panelVentas = new Ventas(nivelUsuario, nombreUsuario);

        botonVentas.addActionListener(this);
        botonVentas.addActionListener(this);
        botonClientes.addActionListener(this);
        botonMotos.addActionListener(this);
        botonUsuarios.addActionListener(this);
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });
        anadirMenu();
        anadirPaneles();
        cambiarTema();
        eventos();

    }// </editor-fold>

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void eventos(){
        generarPDF.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new generadorPDF();
            }
        });
        abrirBBDD.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abrirBBDD();
            }
        });
        verConexion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mostrarConexionActual();
            }
        });

        cerrarSesion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                cerrarSesion();
            }
        });

        cambiarTema.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                cambiarTema();
            }
        });

        estadistica.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                new generadorGraficos();
            }
        });
        contactoNosotros.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new contacto();
            }
        });
    }

    private void cambiarTema(){
        if (modoOscuro){
            botonVentas.setBackground(new Color(246, 231, 23));
            botonClientes.setBackground(new Color(246, 231, 23));
            botonMotos.setBackground(new Color(246, 231, 23));
            botonUsuarios.setBackground(new Color(246, 231, 23));
            jPanel1.setBackground(new Color(118, 118, 118));
            panelSecundario.setBackground(new Color(53, 52, 53));
            panelSecundario.setForeground(new Color(128, 128, 128));
            panelMotos.cambiarTema();
            panelClientes.cambiarTema();
            panelUsuario.cambiarTema();
            panelVentas.cambiarTema();
            modoOscuro = false;
        } else {
            botonVentas.setBackground(new Color(218, 218, 218));
            botonClientes.setBackground(new Color(218, 218, 218));
            botonMotos.setBackground(new Color(218, 218, 218));
            botonUsuarios.setBackground(new Color(218, 218, 218));
            panelSecundario.setBackground(new java.awt.Color(153, 255, 153));
            panelSecundario.setForeground(new java.awt.Color(204, 255, 204));
            jPanel1.setBackground(new java.awt.Color(255, 153, 204));
            panelMotos.cambiarTema();
            panelClientes.cambiarTema();
            panelUsuario.cambiarTema();
            panelVentas.cambiarTema();
            modoOscuro = true;
        }
        System.out.println(tema);

    }

    private void cerrarSesion(){
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazLogin().setVisible(true);
            }
        });

    }

    private void abrirBBDD(){
        JOptionPane.showMessageDialog(null,"Se abrirá SQL Workbench si lo tiene insalado");
        try {
            Desktop.getDesktop().open(new File("C:\\Program Files\\MySQL\\MySQL Workbench 8.0\\MySQLWorkbench.exe"));
        } catch (IOException ioException) {
            JOptionPane.showMessageDialog(null,"No está instalado MySQL Workbench o se ha cambiado su ruta");
        }
    }

    private void mostrarConexionActual(){
        String[] datosConexion = conexion.getRegistros();
        String s = "BBDD: \"Concesionario\"\nRuta: "+datosConexion[0]
                +"\nUsuario: "+datosConexion[1]+"\nClave: "+datosConexion[2];
        JOptionPane.showMessageDialog(this,s,"Datos sobre la conexion", JOptionPane.INFORMATION_MESSAGE);
    }

    private void alterarPermisos(){
        if(nivelUsuario == 1){
            this.botonUsuarios.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainInterface().setVisible(true);
            }
        });
    }

    private void anadirMenu(){
        barra = new JMenuBar();

        //Código para la pestaña de archivo
        menu_archivo = new JMenu("Archivo");
        barra.add(menu_archivo);
        abrirBBDD = new JMenuItem("Abrir BBDD");
        generarPDF = new JMenuItem("Generar PDF");
        estadistica = new JMenuItem("Ver estadísticas");
        menu_archivo.add(abrirBBDD);
        menu_archivo.add(generarPDF);
        menu_archivo.add(estadistica);

        //Código para la pestaña de opciones
        menu_opciones = new JMenu("Opciones");
        barra.add(menu_opciones);
        cambiarTema = new JMenuItem("Cambiar tema");
        verConexion = new JMenuItem("Datos sobre la conexión");
        cerrarSesion = new JMenuItem("Cerrar la sesión");
        menu_opciones.add(verConexion);
        menu_opciones.add(cambiarTema);
        menu_opciones.add(cerrarSesion);

        //Código del menu ayuda


        //Código del menu acerca de
        menu_acerca = new JMenu("Acerca de");
        barra.add(menu_acerca);
        quienesSomos = new JMenuItem("¿Quiénes somos?");
        contactoNosotros = new JMenuItem("¡Contacta con nosotros!");
        menu_acerca.add(quienesSomos);
        menu_acerca.add(contactoNosotros);

        setJMenuBar(barra);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonMotos;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JButton botonVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoMain;
    private javax.swing.JPanel panelSecundario;
    // End of variables declaration

    private void anadirPaneles(){
        panelSecundario.add(panelClientes);
        panelSecundario.add(panelMotos);
        panelSecundario.add(panelVentas);
        panelSecundario.add(panelUsuario);
        panelClientes.setVisible(false);
        panelMotos.setVisible(false);
        panelVentas.setVisible(false);
        panelUsuario.setVisible(false);
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        remove(panelClientes);
        remove(panelMotos);
        remove(panelVentas);
        remove(panelUsuario);
        JButton boton = (JButton) ae.getSource();
        if(boton == botonClientes){
            cambiarPanel(PANEL_CLIENTE);
            setTitle("Concesionario Mercado Corral - Clientes");

        }else if(boton == botonMotos){
            cambiarPanel(PANEL_MOTO);
            setTitle("Concesionario Mercado Corral - Motos");

        }else if(boton == botonVentas){
            panelVentas.setVisible(false);
            cambiarPanel(PANEL_VENTA);
            setTitle("Concesionario Mercado Corral - Ventas");

        }else if(boton == botonUsuarios){
            cambiarPanel(PANEL_USUARIO);
            setTitle("Concesionario Mercado Corral - Usuarios");

        }

    }


    public void cambiarPanel(String panelCambio){
        ocultar();
        anadirPaneles();
        switch(panelCambio){
            case PANEL_CLIENTE:
                panelClientes.fillTable();
                panelSecundario.add(panelClientes);
                this.panelClientes.setVisible(true);
                mostrar();
                break;
            case PANEL_MOTO:
                panelMotos.fillTable();
                panelSecundario.add(panelMotos);
                this.panelMotos.setVisible(true);
                mostrar();
                break;
            case PANEL_USUARIO:
                panelUsuario.fillTable();
                panelSecundario.add(panelUsuario);
                this.panelUsuario.setVisible(true);

                mostrar();
                break;
            case PANEL_VENTA:
                panelVentas.fillTable();
                panelSecundario.add(panelVentas);
                this.panelVentas.setVisible(true);
                mostrar();
                break;
        }
        panelSecundario.repaint();
    }

    public void ocultar(){
        Thread t = new Thread(new esconderPanel(this));
        t.start();

    }

    public void mostrar(){
        Thread o = new Thread(new mostrarPanel(this));
        o.start();
    }

    public void setTema(int tema) {
        this.tema = tema;
    }


    class esconderPanel implements Runnable{

        private JFrame panel;
        //private JPanel referencia;

        public esconderPanel(JFrame panelCambio){
            this.panel = panelCambio; //Panel que va a sufrir el cambio
        }

        @Override
        public void run() {
            int n = panel.getWidth();
            while(n > 255){
                panel.setSize(n, panel.getHeight());
                n-=30;
                try{
                    Thread.sleep(1);
                }catch(InterruptedException io){
                    System.out.println(io.getMessage());
                }
            }
            panel.repaint();
//       while(n < tamOriginal){
//           panel.setSize(n, panel.getHeight());
//           n+=15;
//           try{
//                Thread.sleep(1);
//           }catch(InterruptedException io){}
//       }
        }
    }

    class mostrarPanel implements Runnable{

        private JFrame panel;

        public mostrarPanel(JFrame panelCambio){
            this.panel = panelCambio; //Panel que va a sufrir el cambio
        }

        @Override
        public void run() {
            try{
                Thread.sleep(100);

                int target = panel.getWidth();
                int n = panel.getWidth();
                while(n < 850){
                    panel.setSize(n,panel.getHeight());
                    n += 25;
                    panel.repaint();
                    Thread.sleep(1);
                }
            } catch(InterruptedException e){
                System.out.println(e.getMessage());
            }
            panel.repaint();
        }
    }
}


    
    
    
    
    


