package views.Ventanas.panelesMenu;

import controllers.ControllerConexion;
import controllers.VentaCRUD;
import modelo.Informes;
import utils.estaticas;

import javax.naming.ldap.Control;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

public class generadorPDF extends javax.swing.JDialog implements ActionListener {


    private String rutaGenerarPDF;

    public generadorPDF() {

        setResizable(false);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setModal(true);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        setTitle("Generador de PDF");
        Image icono = Toolkit.getDefaultToolkit().getImage(estaticas.RUTA_IMAGENES+"iconoPDF.png");
        setIconImage(icono);
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioVentasUsuario = new javax.swing.JRadioButton();
        radioVentasMarca = new javax.swing.JRadioButton();
        radioVentas = new javax.swing.JRadioButton();
        radioVentasCliente = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labeDirectorio = new javax.swing.JLabel();
        botonGenerarPDF = new javax.swing.JButton();
        botonSeleccionarDirectorio = new javax.swing.JButton();
        cnVentas = new VentaCRUD();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Generador de documentos PDF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        labelImagen.setIcon(new javax.swing.ImageIcon(estaticas.RUTA_IMAGENES+"iconoPDF.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(labelImagen, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        jPanel2.setBackground(new java.awt.Color(165, 165, 165));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 179));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(radioVentasUsuario);
        radioVentasUsuario.setText("Ventas por usuario");
        radioVentasUsuario.setBackground(new java.awt.Color(165, 165, 165));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 9, 4);
        jPanel2.add(radioVentasUsuario, gridBagConstraints);

        buttonGroup1.add(radioVentasMarca);
        radioVentasMarca.setText("Ventas por marca");
        radioVentasMarca.setBackground(new java.awt.Color(165, 165, 165));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 9, 4);
        jPanel2.add(radioVentasMarca, gridBagConstraints);

        buttonGroup1.add(radioVentas);
        radioVentas.setText("Ventas general");
        radioVentas.setBackground(new java.awt.Color(165, 165, 165));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 19, 13);
        jPanel2.add(radioVentas, gridBagConstraints);

        buttonGroup1.add(radioVentasCliente);
        radioVentasCliente.setText("Ventas por cliente");
        radioVentasCliente.setBackground(new java.awt.Color(165, 165, 165));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 19, 4);
        jPanel2.add(radioVentasCliente, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Selecciona el tipo de documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 8);
        jPanel2.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 180));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Selecciona dónde guardar el fichero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel3.add(jLabel4, gridBagConstraints);

        labeDirectorio.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 7, 5);
        jPanel3.add(labeDirectorio, gridBagConstraints);

        botonGenerarPDF.setText("Generar documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(28, 11, 7, 11);
        jPanel3.add(botonGenerarPDF, gridBagConstraints);

        botonSeleccionarDirectorio.setText("Directorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel3.add(botonSeleccionarDirectorio, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jPanel3, gridBagConstraints);

        this.botonSeleccionarDirectorio.setEnabled(false);
        this.botonGenerarPDF.setEnabled(false);
        eventos();
        pack();
    }// </editor-fold>

    private void eventos(){
        radioVentas.addActionListener(this);
        radioVentasCliente.addActionListener(this);
        radioVentasMarca.addActionListener(this);
        radioVentasUsuario.addActionListener(this);
        this.botonSeleccionarDirectorio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botonMostarChooser();
                botonGenerarPDF.setEnabled(true);
            }
        });
        this.botonGenerarPDF.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                generarPDFs();
            }
        });
    }

    private void generarPDFs(){
        if (radioVentas.isSelected()){
            Informes informe = new Informes(cnVentas, "Ventas", rutaGenerarPDF);
            if(informe.generarInformeVentas()){
                JOptionPane.showMessageDialog(this,  "En la ruta " + rutaGenerarPDF, "Informe generado",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,  "El pdf no se ha podido crear", "Error",JOptionPane.ERROR_MESSAGE);
            }
        }

        if (radioVentasMarca.isSelected()){
            String marca = JOptionPane.showInputDialog("Introduce la marca");
            Informes informe = new Informes(cnVentas, "Ventas de la marca " + marca, rutaGenerarPDF);
            if(informe.generarInformeVentasMarca(marca)){
                JOptionPane.showMessageDialog(this,  "En la ruta " + rutaGenerarPDF, "Informe generado",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,  "El pdf no se ha podido crear", "Error",JOptionPane.ERROR_MESSAGE);
            }
        }

        if (radioVentasCliente.isSelected()){
            String dni = JOptionPane.showInputDialog("Introduce el DNI del cliente");
            Informes informe = new Informes(cnVentas, "Ventas del cliente con DNI " + dni, rutaGenerarPDF);

            if(informe.generarInformeVentasClientes(dni)){
                JOptionPane.showMessageDialog(this,  "En la ruta " + rutaGenerarPDF, "Informe generado",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El pdf no se ha podido crear","Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        if (radioVentasUsuario.isSelected()){
            String nick = JOptionPane.showInputDialog("Introduce el nick del usuario");
            Informes informe = new Informes(cnVentas, "Ventas del usuario " + nick, rutaGenerarPDF);

            if(informe.generarInformeVentasUsuario(nick)){
                JOptionPane.showMessageDialog(this,  "En la ruta " + rutaGenerarPDF, "Informe generado",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,  "El pdf no se ha podido crear", "Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void botonMostarChooser(){
        JFileChooser directorios = new JFileChooser();
        directorios.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        directorios.showDialog(this,"Seleccionar carpeta");
        rutaGenerarPDF = directorios.getSelectedFile().getAbsolutePath();
        this.labeDirectorio.setText(truncarRuta(rutaGenerarPDF));

    }

    public String truncarRuta(String ruta){
        if(ruta.length()>40){
            return ruta.substring(0,40)+"...";
        }else{
            return ruta;
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton botonGenerarPDF;
    private javax.swing.JButton botonSeleccionarDirectorio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labeDirectorio;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JRadioButton radioVentas;
    private javax.swing.JRadioButton radioVentasCliente;
    private javax.swing.JRadioButton radioVentasMarca;
    private javax.swing.JRadioButton radioVentasUsuario;
    private VentaCRUD cnVentas;

    @Override
    public void actionPerformed(ActionEvent e) {
        JRadioButton radio = (JRadioButton) e.getSource();
        if(radio.isSelected()){
            this.botonSeleccionarDirectorio.setEnabled(true);
        }
    }
    // End of variables declaration
}
